consul.tf
gluster.tf
mesos-cluster.tf
modules/mesos-cluster/main.tf
modules/mesos-cluster/security-groups.tf
modules/mesos-cluster/variables.tf
network.tf
variables.tf
vpn.tf

https://pastebin.mozilla.org/8864049
I also styled the code to make it easier to read.

Add nemo's suggestions, style code

---

network.tf

Fixes #3, has not been applied yet.
- Add Peering connection between apps-production-vpc and apps-staging-vpc
- Add ACL rule to deny all traffic between the VPCs
- Add ACL rule to allow Consul RPC (8300), Serf LAN (8301) and WAN (8302) between the VPCs

Fix Consul health checks flapping

---

admin.tf
terraform.tf

- Add IAM role for admin node
- Add admin node security groups
- Add admin node instance
- Add S3 bucket for Terraform sync

Add admin node

---

db.tf
modules/mesos-cluster/security-groups.tf

- Create RDS subnet group
- Create RDS security group
- Expose Mesos slave SG IDs
- Create MySQL shared RDS instance

Add MySQL shared DB instance

---

.gitignore
network.tf
terraform.tf

- Move meta resources to terraform.tf
- Enable versioning on the S3 bucket
- Add Terraform remote state
- Add .gitignore for state/var files

Add S3 remote state sync

---

admin.tf

- Add ELB in front of admin node
- Add SG & rules to allow HTTP traffic to admin node

Make Jenkins public

---

distributions.tf

Add activate.mozilla.community CloudFront module

---

distributions.tf

https://bugzilla.mozilla.org/show_bug.cgi?id=1301082

[Bug 1301082] Deploy CloudFront for campus.mozilla.community

---

jenkins-public.tf
storage.tf

- Create SG and instance
- Create EFS

Add resources for public Jenkins instance

---

jenkins-public.tf
modules/mesos-cluster/security-groups.tf

- Enable Framework port for Mesos

Use the correct cert for public Jenkins

---

db.tf

let it be known that i fixed a huge mess of commits by using `git push --force`

Add new postgres shared server configuration

---

db.tf

Add Postgres ports from staging and production

---

admin.tf
jenkins-public.tf

Allow registry traffic from Mesos slaves

---

backups.tf
modules/mesos-cluster/backups.tf

* Mesos-{master,slave}
* Jenkins private
* Jenkins public

Add S3 buckets to facilitate for duplicity backup backends

---

bitergia.tf

for https://github.com/mozilla/participation-metrics-org/issues/58

Add Amazon ElasticSearch instance for Rust analytics

---

storage.tf

* Rename jenkins-efs-sg to admin-efs-sg

Add EFS endpoint for grafana persistent storage

---

iam.tf

- Add group with RO permissions
- Add role with RW permissions for MFA users

Add Community Ops IAM group and role

---

iam.tf

- Make modifying MFA from console work

Add Ops group permissions to role

---

terraform.tf

this has to be done first from terraform 0.8

Remove terraform remote state resource

---

iam.tf

IAM read-only role

---

discourse.tf
modules/discourse/main.tf

This broke everything and generally isn't worth messing with

Revert bucket policies for Discourse

---

consul.tf
jenkins-public.tf
modules/mesos-cluster/main.tf
vpn.tf

* Attach SNS full access policy to be able to send logs

Add instance profiles to all ec2 instances.

---

mesos-cluster.tf

I'm going to scale down to three until we discuss resource usage again, since two might not be enough.

Scale production slaves down

---

.gitignore
db.tf
modules/mesos-cluster/main.tf
modules/mozillians/main.tf
mozillians.tf

- Production slaves
- Production DB
- Staging ES/EC

Add infrastructure for Mozillians

---

modules/mesos-cluster/main.tf
variables.tf

Reverts mozilla/partinfra-terraform#129
We don't need it anymore

Revert "Add ELB for mozillians.org"

---

dns/mozilla-lt.tf
dns/mozilla-se.tf
dns/mozillabr-org.tf
dns/mozillaindia-org.tf

- mozillaindia.org
- mozillabr.org
- mozilla.se
- mozilla.lt

Add DNS data resources for community sites

---

consul.tf
coss.tf
discourse.tf
iam.tf
jenkins-public.tf
mesos-cluster.tf
modules/discourse/iam.tf
modules/mesos-cluster/iam.tf
modules/mesos-cluster/main.tf
modules/mozillians/iam.tf
modules/remo/iam.tf
mozillians.tf
remo.tf
variables.tf
vpn.tf

A crappy diagram of what this is supposed to do

IAM refactoring and additions

---

bitergia.tf
variables.tf

- Scale up EBS volume on new server

Remove old bitergia server

---

modules/discourse-tldr/main.tf

https://github.com/mozilla/discourse-tldr/releases/tag/v1

bump discourse-tldr version

---

distributions.tf

@johngian r?
Issue for it: https://github.com/mozilla/parsys/issues/320

Add voice-sprint.mozilla.community

---

modules/discourse-tldr/main.tf

This is causing mailchimp emails to bounce

disable tls requirement for discourse tldr
